env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  'no-undef': 'off'
  'no-case-declarations': 'off'
  'require-yield': 'off'
