env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - '@stylistic'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - args: all
      argsIgnorePattern: '^_'
      caughtErrors: all
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      ignoreRestSiblings: true

  # Style rules
  # Only adding some rules here to start.
  # See https://eslint.style/rules for a complete
  # list, and add more when given time.
  '@stylistic/arrow-parens': 'error'
  '@stylistic/arrow-spacing': 'error'
  '@stylistic/block-spacing': 'error'
  '@stylistic/brace-style': 'error'
